-- An uncapped goal list, and the free text behind the `Other` hobby (§2.1).
--
-- Generated, and kept as generated: both columns are plain ADD COLUMNs with no
-- CHECK, so drizzle-kit had no table-level constraint to render and did not
-- reach for the rebuild that 0003 and 0004 had to be hand-written to avoid.
--
-- `goal_keys` is JSON, and deliberately not a join table or more numbered
-- columns. Signup no longer caps the goal picker, but goals past the second are
-- not filter targets: matching and the directory read `goal_key` and
-- `goal_key_2`, which stay indexed, CHECK-constrained and authoritative, and
-- which PATCH /me derives from this list's first two entries. What the list
-- adds is the rest of the answer and the order it was given in — and order is
-- exactly what `user_tags` does not store.
--
-- No membership CHECK on it, following `country` in 0004: a constraint over a
-- JSON array could only ever be widened by rebuilding the table, and Zod
-- already rejects any key outside GOAL_KEYS on the way in.
ALTER TABLE `users` ADD `goal_keys` text;--> statement-breakpoint
-- The `custom` hobby's text, mirroring goal_text and major_text. Nullable:
-- everyone who onboarded before `Other` existed has no such hobby.
ALTER TABLE `users` ADD `interest_text` text;
