import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * One flat config for the whole monorepo.
 *
 * Type-aware linting is deliberately off. The rules that catch real bugs here
 * (unused values, floating promises in a few spots) are largely already enforced
 * by `tsc` under the strict settings in tsconfig.base.json, and turning on
 * project-service type checking across three packages — one of which is React
 * Native — roughly quadruples lint time for rules that overlap what typecheck
 * already fails on. Lint covers what types cannot.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.expo/**',
      '**/.wrangler/**',
      // Generated by `wrangler types`, and thousands of lines of runtime types.
      'apps/api/worker-configuration.d.ts',
      // Generated SQL snapshots.
      'apps/api/drizzle/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // tsconfig's noUnusedLocals already fails the build on these, but the
      // lint message points at the argument rather than the whole signature.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      // The codebase uses `as never` in a handful of places to satisfy Hono's
      // generated client types; banning it outright would mean disabling it
      // inline everywhere instead.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-console': 'off', // Worker logs are the only observability in dev.
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },

  {
    /**
     * Ambient declaration files. A global `declare namespace` cannot use a
     * top-level import without becoming a module, so `import()` types are the
     * only way to reference another module from inside one.
     */
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },

  {
    /**
     * Build-tool configs that must stay CommonJS: Metro, Babel, Jest and
     * Tailwind all load these with `require`, so they cannot become ESM.
     */
    files: ['**/*.config.js', '**/babel.config.js', '**/metro.config.js'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        module: 'writable',
        require: 'readonly',
        __dirname: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  {
    // Test files legitimately use non-null assertions on fixtures they just
    // created, and empty catch blocks to assert a throw.
    files: ['**/test/**/*.ts', '**/__tests__/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
);
